sitemap redesign
hlxsites/moleculardevices pull request #1090
Opened 2023-08-21 08:21 UTC by dev-rajneeshkumar

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/sitemap
- After: https://sitemap-update--moleculardevices--hlxsites.hlx.page/sitemap

2023-08-21 08:24 UTC, dev-rajneeshkumar commented
Hi All,

Please review and approve PR to update sitemap as per below docs.
<img width="647" alt="image" src="https://github.com/hlxsites/moleculardevices/assets/42608830/7d3d1c09-6f51-4787-be0a-f7fc51c8ca61">


[sitemap (1).xlsx](https://github.com/hlxsites/moleculardevices/files/12393885/sitemap.1.xlsx)
Regards,
Rajneesh

2023-08-30 07:37 UTC, alexcarol approved these changes

2023-08-30 07:39 UTC, mhaack requested changes

2023-08-30 07:39 UTC, mhaack commented on blocks/columns/columns.css
> +  font-family: 'Proxima Nova Light';
This should either be removed or use the font variable.

2023-09-26 13:03 UTC, merged