Issue 1152 - Add Molecular Devices at the end of the title
hlxsites/moleculardevices pull request #1153
Opened 2023-08-31 15:51 UTC by alexcarol

Fix #1152

Test URLs:
Homepage (nothing is appended)
Before: https://main--moleculardevices--hlxsites.hlx.page/
After: https://issue-1152--moleculardevices--hlxsites.hlx.page/

Products page (Molecular devices is appended) - should work for any page that is not the homepage
Before: https://main--moleculardevices--hlxsites.hlx.page/products
After: https://issue-1152--moleculardevices--hlxsites.hlx.page/products

2023-08-31 16:09 UTC, mhaack requested changes

2023-08-31 16:09 UTC, mhaack commented on scripts/scripts.js
> +  }
I think we can directly use `document.title`. Something like or similar should do the trick:

```
document.title = document.title || document.title + ' | Molecular Devices'
```

2023-08-31 16:18 UTC, alexcarol commented on scripts/scripts.js
> +  }
Done

2023-09-01 07:11 UTC, RajMankotia commented
it looks good for -https://main--moleculardevices--hlxsites.hlx.page/products

2023-09-01 07:13 UTC, mhaack approved these changes

2023-09-01 07:14 UTC, merged