IP Checker API integration to store user data
hlxsites/moleculardevices pull request #353
Opened 2023-05-14 11:27 UTC by lydiapuric

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #182

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/
- After: https://ipstack-integration--moleculardevices--hlxsites.hlx.page/

2023-05-15 05:10 UTC, mhaack requested changes

2023-05-15 05:10 UTC, mhaack commented on scripts/scripts.js
> +function loadDelayed() {
Don’t touch `loadDelayed` here. The entire `loadUserData` function should go into `delayed.js`. I think we don’t even have to do anything for this in `scrips.js`.

2023-05-15 05:58 UTC, lydiapuric commented
I wanted to use the functions for getting and setting the cookie from scripts.js. Putting te new function into delayed.js, and using functions from scripts.js, causes a circular dependency I wanted to avoid. On 15 May 2023, at 07:10, Markus Haack ***@***.***> wrote:﻿
@mhaack requested changes on this pull request.



In scripts/scripts.js:
> +      return Promise.reject(response);
+    }).then((data) => {
+      if (!getCookie(countryCodeInfo)) {
+        setCookie(countryCodeInfo, data[countryCodeInfo], 30);
+      }
+    }).catch((err) => {
+      // eslint-disable-next-line no-console
+      console.warn('Could not load user information.', err);
+    });
+}
+
+/**
+ * loads everything that happens a lot later, without impacting
+ * the user experience.
+ */
+function loadDelayed() {

Don’t touch loadDelayed here. The entire loadUserData function should go into delayed.js. I think we don’t even have to do anything for this in scrips.js.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-05-15 06:48 UTC, lydiapuric commented on scripts/scripts.js
> +function loadDelayed() {
I see we ignored the circular dependency already  with drift. Moving... note: this is still a draft PR, the testing and update is missing

2023-05-15 06:58 UTC, mhaack commented
> I wanted to use the functions for getting and setting the cookie from scripts.js. Putting te new function into delayed.js, and using functions from scripts.js, causes a circular dependency I wanted to avoid. 

Understood, but I think this is fine. `Scrips.js` is always loaded before `delay.js` so nothing bad will happen. Also conceptuallly in Franklin everything loaded delayed should be in `delayed.js`.

2023-05-15 07:15 UTC, lydiapuric commented
ThanksYes, but still didn't like it ;) Added it now in delayed.js - however the PR is still WIP and still does not overcome CORS 🤪Soon, I will set up my localhost, so I can simulate the CORS issue locallyOn 15 May 2023, at 09:00, Markus Haack ***@***.***> wrote:﻿
Also check we already have // eslint-disable-next-line import/no-cycle from the boilerplate in delayed.js

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-05-15 18:14 UTC, mhaack commented on scripts/scripts.js
> +export function handleUpdateUserDataEvent(event, userData) {
When is this function used?

2023-05-15 19:32 UTC, lydiapuric commented on scripts/scripts.js
> +export function handleUpdateUserDataEvent(event, userData) {
It is not used, I thought about adding a simple helper function for future events. I can remove that function.

2023-05-15 19:35 UTC, lydiapuric commented on scripts/scripts.js
> +export function handleUpdateUserDataEvent(event, userData) {
Function handleUpdateUserDataEvent is removed.

2023-05-15 19:49 UTC, mhaack commented
Code LGTM. Can not test as I run into `Error code 104 occured while loading user information. usage_limit_reached: Your monthly usage limit has been reached. Please upgrade your Subscription Plan.`

@kapildhiman I think we need the real account key here. The limit of the free key is too low and it will be blocked again quickly if we merge this to main.

2023-05-15 19:54 UTC, jose-correia commented
Code also LGTM.
Probably not related to these changes but the TBT looks a bit off-place here. Did you rebase with the newest changes to the megamenu, or is this related to another thing?

2023-05-16 08:27 UTC, lydiapuric commented
Thanks @mhaack and @jose-correia. @jose-correia I just merged with main, TBT looks good now.

2023-05-16 13:01 UTC, mhaack approved these changes

2023-05-16 13:20 UTC, merged