feat: implement product specs tab
hlxsites/moleculardevices pull request #407
Opened 2023-05-22 15:27 UTC by duynguyen

Fix #370 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/absorbance-readers/spectramax-quickdrop-micro-volume-spectrophotometer#specifications-options
- After: https://370-product-specs--moleculardevices--hlxsites.hlx.page/products/microplate-readers/absorbance-readers/spectramax-quickdrop-micro-volume-spectrophotometer#specifications-options

AND: https://370-product-specs--moleculardevices--hlxsites.hlx.page/products/flipr-penta-high-throughput-cellular-screening-system#specifications-options

AND: https://370-product-specs--moleculardevices--hlxsites.hlx.page/products/microplate-readers/absorbance-readers/spectramax-abs-plate-readers

2023-05-24 14:03 UTC, jose-correia requested changes
In the original website the "Request Quote" container is sticky when we scroll down.

We already support this, theoretically its just a matter of adding `sticky-element sticky-desktop sticky-mobile` classes to the block in the content document

2023-05-24 14:07 UTC, jose-correia requested changes
The right column, with the grey rows should be a bit bigger, with 730px of width instead of 570px.

May become noticeable in cells that have a lot of text

2023-05-24 17:18 UTC, duynguyen commented
@jose-correia fixed `The right column, with the grey rows should be a bit bigger`.

I would defer the sticky table head to a follow-up issue #434. It might require a handful of JS scripts.

2023-05-25 16:12 UTC, jose-correia approved these changes

2023-05-30 09:19 UTC, merged