Shopify integration
hlxsites/moleculardevices pull request #438
Opened 2023-05-25 11:52 UTC by lydiapuric

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/igg-quantification-assays/clonedetect#ordering-options
- After: https://shopify-integration--moleculardevices--hlxsites.hlx.page/products/assay-kits/igg-quantification-assays/clonedetect#ordering-options

2023-05-25 12:37 UTC, lydiapuric commented
Note: As confirmed via Slack by @kapildhiman: Store feature will only work in subdomains of http://moleculardevices.com

2023-06-01 05:36 UTC, dev-rajneeshkumar commented
Hi @lydiapuric  can't see add to cart button option in the order tab. I am checking in US zone.
![add-to-cart](https://github.com/hlxsites/moleculardevices/assets/42608830/4d2ebb42-cb21-4ba3-bb3d-336d66a71cc5)

2023-06-01 08:53 UTC, jose-correia requested changes

2023-06-01 08:53 UTC, jose-correia commented on blocks/ordering-options/ordering-options.js
> +  return fetch('https://shop.moleculardevices.com/cart.json', {
I see this `baseUrl` in multiple places, should we maybe have a centralized variable:

```javascript
const SHOP_BASE_URL = 'https://shop.moleculardevices.com'
```

2023-06-01 12:33 UTC, jose-correia approved these changes

2023-06-01 13:19 UTC, merged