fix: leadership page
hlxsites/moleculardevices pull request #546
Opened 2023-06-02 14:57 UTC by paolomoz

Fix #519

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/leadership
- After: https://issue-519--moleculardevices--hlxsites.hlx.page/leadership

2023-06-02 15:01 UTC, paolomoz commented
The main fix here was to add /leadership breadcrumb:auto in metadata.xlsx

2023-06-02 15:04 UTC, jose-correia requested changes

2023-06-02 15:04 UTC, jose-correia commented on styles/styles.css
> +  text-align: center;
This change affects other headers throughout the website. For instance in the header. Cant we make it more specific?

2023-06-03 06:39 UTC, paolomoz commented on styles/styles.css
> +  text-align: center;
@jose-correia I made it general on purpose. The idea is: H1 is always centered if it is in the content and not if it is in the header. H1 cannot be anywhere, right? The header case is covered 2 lines below :) 
I see your point but at the same time I didn't want to fix this specific page only but potentially all occurrencies.
If you have an example where H1 (not in header) should be aligned different, it would be great so we can make this more specific

2023-06-03 06:42 UTC, paolomoz commented
I noticed that https://main--moleculardevices--hlxsites.hlx.page/leadership broke since yesterday, both in main and in this branch. I think this is due to a content change. 
I see this in console: 
`failed to load module for leader-profiles TypeError: Failed to fetch dynamically imported module: https://main--moleculardevices--hlxsites.hlx.page/blocks/leader-profiles/leader-profiles.js`

2023-06-05 09:19 UTC, alexcarol commented
> this page is not broken due to content change made by @alexcarol working on #551 If possible it would be better to work on draft content until the change is complete

Sorry about that, merged the fix, feel free to rebase.

2023-06-05 09:40 UTC, jose-correia approved these changes

2023-06-05 09:53 UTC, merged