thank you page content
hlxsites/moleculardevices pull request #570
Opened 2023-06-05 15:29 UTC by paolomoz

Fix #564

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/ebook/br/elisa?page=thankyou
- After: https://thank-you-lp--moleculardevices--hlxsites.hlx.page/en/assets/ebook/br/elisa?page=thankyou

2023-06-06 09:49 UTC, lydiapuric requested changes
Mobile version is not styled and is broken
<img width="720" alt="Screenshot 2023-06-06 at 11 49 31" src="https://github.com/hlxsites/moleculardevices/assets/3846840/08b3f4d4-4b16-43d4-b625-ac82aa2f0098">

2023-06-06 13:36 UTC, paolomoz commented on scripts/scripts.js
> +  const skipWave = document.querySelector('.page-tabs, .thankyou, .section.wave:last-of-type, .section:last-of-type div:first-of-type .fragment:only-child');
@mhaack could you please check if this change is acceptable? 
pros: easier to add special cases + 90% less code
cons: last minute change, maybe you prefer to keep code and make small patches to it. LMK

2023-06-06 13:53 UTC, mhaack commented on scripts/scripts.js
> +  const skipWave = document.querySelector('.page-tabs, .thankyou, .section.wave:last-of-type, .section:last-of-type div:first-of-type .fragment:only-child');
Yes, looks ok to me

2023-06-06 13:53 UTC, mhaack commented on styles/styles.css
> +  display: block;
Why this in styles.css and not in landing-page.css?

2023-06-07 06:33 UTC, paolomoz commented
@mhaack @lydiapuric your suggestions have been address; please review. thanks

2023-06-07 09:20 UTC, mhaack approved these changes

2023-06-07 12:54 UTC, merged