chore: add product carousel
hlxsites/moleculardevices pull request #579
Opened 2023-06-06 16:24 UTC by mhaack

Adds product carousel (without compare) used on product categories and events pages.

Fix #575
Relates to #523

Test URL with large list of products
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers
- After: https://product-carousel--moleculardevices--hlxsites.hlx.page/products/microplate-readers

Test URL with short list of products
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/washers
- After: https://product-carousel--moleculardevices--hlxsites.hlx.page/products/microplate-readers/washers

Test URL with short list of products
- Before: https://main--moleculardevices--hlxsites.hlx.page/events/biophysical-society-baltimore
- After: https://product-carousel--moleculardevices--hlxsites.hlx.page/events/biophysical-society-baltimore

2023-06-06 16:30 UTC, jose-correia commented
In the first example https://product-carousel--moleculardevices--hlxsites.hlx.page/products/microplate-readers are we ditching the original behaviour where we can go from the first item to the last by clicking the left arrow?
I remember we already supported this in the card carousel code

2023-06-06 16:30 UTC, jose-correia requested changes

2023-06-06 16:30 UTC, jose-correia commented on blocks/product-carousel/product-carousel.js
> +      infiniteScroll: false,
this should be true no?

2023-06-06 16:32 UTC, mhaack commented on blocks/product-carousel/product-carousel.js
> +      infiniteScroll: false,
You are right, fixed

2023-06-06 18:01 UTC, andreituicu approved these changes
There are some defects, please see the comments below. 

Overall the code looks ok.

2023-06-07 09:27 UTC, mhaack commented on blocks/product-carousel/product-carousel.js
> +      navButtons: window.matchMedia('only screen and (max-width: 767px)').matches || products.length > 3,
Fixed in combination with `infiniteScroll: products.length > 3` for <= 3 there is no scroll on desktop and items should not repeat. Only on smaller screens scroll is needed.

2023-06-07 09:29 UTC, jose-correia approved these changes

2023-06-07 09:42 UTC, merged