Implement "featured highlights" on product landing page
hlxsites/moleculardevices pull request #667
Opened 2023-06-20 04:53 UTC by paolomoz

Fix #649

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/
- After: https://issue-648--moleculardevices--hlxsites.hlx.page/

2023-06-20 08:06 UTC, jose-correia requested changes

2023-06-20 08:06 UTC, jose-correia commented on blocks/featured-highlights/featured-highlights.css
> +}
I think we need a more specific class for the caption below the picture because it uses `Proxima Nova Light`, and currently its set to `Proxima Nova Regular`

2023-06-20 08:06 UTC, jose-correia commented on blocks/featured-highlights/featured-highlights.js
> +  decorateIcons(slider);
We need to add the link icon to the `Learn More` button right?
We just need to query for the `<a title='Learn More'>` and append a `span({ class: 'icon icon-icon_link' });`

2023-06-22 07:34 UTC, andreituicu commented
@paolomoz the new block is getting flagged for high CLS on Desktop, causing low LHS.

<img width="729" alt="Screenshot 2023-06-22 at 09 31 55" src="https://github.com/hlxsites/moleculardevices/assets/3651689/7b7a14ad-989a-48a0-979d-7df313409eed">
<img width="741" alt="Screenshot 2023-06-22 at 09 31 46" src="https://github.com/hlxsites/moleculardevices/assets/3651689/2f230655-5b1b-4f09-8f71-e2d1addd302e">

2023-06-22 09:44 UTC, duynguyen commented
The mobile view seems a bit off to me. the new block could extend the page width, hence breaking other blocks as well.

2023-06-22 19:19 UTC, andreituicu approved these changes

2023-06-23 03:46 UTC, merged