Issue 817 - Fix microplate readers styling
hlxsites/moleculardevices pull request #850
Opened 2023-07-06 15:06 UTC by alexcarol

Fix #817 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers
- After: https://issue-817--moleculardevices--hlxsites.hlx.page/products/microplate-readers

2023-07-06 16:09 UTC, mhaack requested changes

2023-07-06 16:09 UTC, mhaack commented on templates/category/category.css
Please move this to styles css. Should work with `.category main h2` etc. as well. No need to add another file which adds a new request. Also this leads to a 404 as the logic try to load `category.js`.

2023-07-07 08:19 UTC, alexcarol commented on templates/category/category.css
Done, after applying the suggested changes and removing redundant css this PR becomes quite small (though I suspect it has to do with work that has happened in parallel to this PR)

2023-07-07 14:51 UTC, mhaack commented
LGTM. Did you cross check with other category pages?

2023-07-07 14:51 UTC, mhaack approved these changes

2023-07-07 16:06 UTC, alinarublea approved these changes

2023-07-07 16:51 UTC, mhaack commented
@alexcarol found one more detail on the Microplate Readers page, on mobile the color is wrong. Can you fix that as well please. 

![IMG_7269](https://github.com/hlxsites/moleculardevices/assets/2643450/e7917876-b29d-4c4d-8b37-41712bc59a40)

2023-07-10 13:23 UTC, alexcarol commented
> @alexcarol found one more detail on the Microplate Readers page, on mobile the color is wrong. Can you fix that as well please.
> 
> ![IMG_7269](https://user-images.githubusercontent.com/2643450/251806174-e7917876-b29d-4c4d-8b37-41712bc59a40.png)

I implemented a fix for that. The only drawback is that it changes the order of the "even" rows on mobile, but it dramatically simplifies CSS. If you think that could be a problem I can write an alternative implementation with the fixes, but it probably makes sense to do it in JS (and have a "light" and a "dark grey" class being applied depending on display size).

2023-07-10 15:06 UTC, alexcarol commented
> LGTM. Did you cross check with other category pages?

I did cross check with some and everything works as expected

2023-07-10 16:19 UTC, alexcarol commented on styles/styles.css
> +
In the page linked in #862 it does cause some changes, but it does look closer to the original site style (compared to what we have now).

2023-07-10 16:49 UTC, mhaack approved these changes

2023-07-11 06:31 UTC, merged