Issue 859 - Fix 3D Biology page issues
hlxsites/moleculardevices pull request #905
Opened 2023-07-13 15:39 UTC by alexcarol

Fix #859 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/3d-biology
- After: https://issue-859--moleculardevices--hlxsites.hlx.page/products/3d-biology

2023-07-13 15:43 UTC, mhaack requested changes

2023-07-13 15:43 UTC, mhaack commented on scripts/scripts.js
> +
Don't do this, familyID is data and we should not mix data & styling. This leads to errors and is easy to break. Also if customer wants a new page with similar styles on a different page this will break.

Introduce a "Theme" meta filed here, that is exactly what we have that for. See /video-gallery for example, which has the same pattern.

2023-07-13 15:57 UTC, alexcarol commented on scripts/scripts.js
> +
Fixed

2023-07-13 16:22 UTC, mhaack commented on styles/styles.css
> +  color: #6eb43f;
`—text-green` can be used here.

2023-07-14 06:35 UTC, alexcarol commented on styles/styles.css
> +  text-align: center;
I was trying to avoid creating a new section just for the title, as that also introduces extra padding. What would be your recommended approach to center only a title? Is there any workaround for the padding issue?

2023-07-14 06:46 UTC, mhaack commented on styles/styles.css
> +  text-align: center;
Ok I see the point with the section and the padding. Lets add then `.title-center h2` and maybe `.title-center h4` as well. So we can use this on other places. I know some places we have extra sections just to center the title. These can use this new section style as well.

2023-07-14 06:46 UTC, mhaack approved these changes

2023-07-14 06:55 UTC, alexcarol commented on styles/styles.css
> +  text-align: center;
Done

2023-07-14 06:56 UTC, merged